### ISSUE TITLE
Open source and partner/external announcement

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-icons#352]
At the moment, polaris-icons is closed-source and we haven't announced it to partners.

We want to unveil the project to the partner community, and raise awareness that they can browse icons on polaris-icons.shopify.com, so they start using this in their React apps and in their ports of Polaris in other languages.

### Tasks

- [x] BLOCKER: Get approval from stakeholders
- [x] BLOCKER: Get approval from Legal
- [x] Add website to `@shopify/polaris-icons`'s `package.json`
- [x] Date: week of June 17th
- [x] Get the repository ready for contributions
  - [x] Contribution guidelines
  - [x] Install CLA Bot
  - [x] Code of conduct (refer to polaris-react's one)
- [ ] Update the style guide
  - [x] Update https://polaris.shopify.com/components/images-and-icons/icon
  - [x] Update https://polaris.shopify.com/design/icons
  - [ ] ~Update https://polaris.shopify.com~
- [x] Get messaging ready
  - [x] Twitter
  - [ ] Partners blog cross posting with Shopify UX
  - [ ] Engineering blog
  - [x] Unite comms? -> NO
- [x] External marketing (Dan)
  - [x] Submit to design websites

**Comment by amrocha** [comment]
Are we good to close this?

**Comment by kaelig** [comment]
Yep! Now closing it. Blog posts remain to be written. We can discuss in a future sync if that's something we can take time to do.
